sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1
  - TWISTED_VERSION=15.4

matrix:
  exclude:
    - python: "3.2"
      env: FLASK_VERSION=0.9
    - python: "3.2"
      env: TWISTED_VERSION=15.4
    - python: "3.3"
      env: FLASK_VERSION=0.9
    - python: "3.4"
      env: FLASK_VERSION=0.9

install:
  - if [ -v FLASK_VERSION ]; then pip install Flask==$FLASK_VERSION; fi
  - if [ -v TWISTED_VERSION ]; then pip install Twisted==$TWISTED_VERSION service_identity pyOpenSSL; fi

script:
  - python setup.py test


